using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using UnityEngine;

namespace MissileFollowCam
{
    // MyPluginInfo.* is auto-generated by BepInEx.PluginInfoProps from the .csproj.
    [BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
    [BepInProcess("NuclearOption.exe")]   // single-player exe only (our scope)
    public class Plugin : BaseUnityPlugin
    {
        internal static ManualLogSource Log = null!;

        // Two cycle keys plus a return-to-aircraft key. All are configurable in the game's BepInEx
        // config menu. The game's native "Switch View" key (L) is left untouched, so it still cycles
        // through the followed missile's camera angles.
        private ConfigEntry<KeyboardShortcut> _cycleNext = null!;
        private ConfigEntry<KeyboardShortcut> _cyclePrev = null!;
        private ConfigEntry<KeyboardShortcut> _returnToAircraft = null!;

        private readonly MissileTracker _tracker = new MissileTracker();
        private int _cursor = -1;

        private void Awake()
        {
            Log = Logger;

            _cycleNext = Config.Bind("Controls", "CycleNextMissile",
                new KeyboardShortcut(KeyCode.RightBracket),   // default ]
                "Follow the NEXT of your in-flight missiles.");
            _cyclePrev = Config.Bind("Controls", "CyclePreviousMissile",
                new KeyboardShortcut(KeyCode.LeftBracket),    // default [
                "Follow the PREVIOUS of your in-flight missiles.");
            _returnToAircraft = Config.Bind("Controls", "ReturnToAircraft",
                new KeyboardShortcut(KeyCode.Semicolon),      // default ;
                "Return the camera to your aircraft's cockpit view.");

            Log.LogInfo($"{MyPluginInfo.PLUGIN_NAME} v{MyPluginInfo.PLUGIN_VERSION} loaded. " +
                        $"Next=[{_cycleNext.Value}] Prev=[{_cyclePrev.Value}] " +
                        $"Return=[{_returnToAircraft.Value}].");
        }

        private void Update()
        {
            // Single-player, live mission only. Otherwise stay out of the way.
            if (!GameBridge.InSinglePlayerMission())
            {
                _tracker.DetachIfNeeded(null);
                _cursor = -1;
                return;
            }

            // Keep the tracker subscribed to the CURRENT local aircraft (handles respawns/aircraft swaps).
            var aircraft = GameBridge.GetLocalAircraft();
            _tracker.EnsureAttached(aircraft);

            if (_cycleNext.Value.IsDown()) Cycle(+1);
            else if (_cyclePrev.Value.IsDown()) Cycle(-1);
            else if (_returnToAircraft.Value.IsDown()) ReturnToAircraft();

            // NOTE: we do NO per-frame camera override. We only switch on a keypress, using the
            // game's own follow path. The native "Switch View" key (L) is left free to cycle the
            // followed missile's camera angles, and we never touch the (aircraft-driven, 2D)
            // RWR/warning audio path.
        }

        private void Cycle(int direction)
        {
            var missiles = _tracker.LiveMissiles();   // pruned, in launch order
            if (missiles.Count == 0)
            {
                Log.LogInfo("No in-flight missiles of yours to follow.");
                _cursor = -1;
                return;
            }

            _cursor = ((_cursor + direction) % missiles.Count + missiles.Count) % missiles.Count;
            GameBridge.FollowUnit(missiles[_cursor]);
            Log.LogInfo($"Following missile {_cursor + 1}/{missiles.Count}. " +
                        $"Press [{_returnToAircraft.Value}] to return to your aircraft.");
        }

        private void ReturnToAircraft()
        {
            GameBridge.ReturnToAircraft();
            _cursor = -1;   // next cycle starts from the first missile again
            Log.LogInfo("Returned to your aircraft.");
        }
    }
}