using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using UnityEngine;

namespace MissileCamNO
{
    // MyPluginInfo.* is auto-generated by BepInEx.PluginInfoProps from the .csproj.
    [BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
    [BepInProcess("NuclearOption.exe")]   // single-player exe only (our scope)
    public class Plugin : BaseUnityPlugin
    {
        internal static ManualLogSource Log = null!;

        // Two cycle keys plus a return-to-aircraft key. All are configurable in the game's BepInEx
        // config menu. The game's native "Switch View" key (L) is left untouched, so it still cycles
        // through the followed missile's camera angles.
        private ConfigEntry<KeyboardShortcut> _cycleNext = null!;
        private ConfigEntry<KeyboardShortcut> _cyclePrev = null!;
        private ConfigEntry<KeyboardShortcut> _returnToAircraft = null!;

        // Automatically snap back to the cockpit a few seconds after your last in-flight missile
        // detonates, so you're not left staring at empty sky. Both configurable.
        private ConfigEntry<bool> _autoReturnEnabled = null!;
        private ConfigEntry<float> _autoReturnDelay = null!;

        private readonly MissileTracker _tracker = new MissileTracker();
        private int _cursor = -1;

        // Scheduled time (Time.time) for the pending auto-return, or a negative value when none is armed.
        private float _autoReturnAt = -1f;

        private void Awake()
        {
            Log = Logger;

            _cycleNext = Config.Bind("Controls", "CycleNextMissile",
                new KeyboardShortcut(KeyCode.RightBracket),   // default ]
                "Follow the NEXT of your in-flight missiles.");
            _cyclePrev = Config.Bind("Controls", "CyclePreviousMissile",
                new KeyboardShortcut(KeyCode.LeftBracket),    // default [
                "Follow the PREVIOUS of your in-flight missiles.");
            _returnToAircraft = Config.Bind("Controls", "ReturnToAircraft",
                new KeyboardShortcut(KeyCode.Semicolon),      // default ;
                "Return the camera to your aircraft's cockpit view.");

            _autoReturnEnabled = Config.Bind("Behavior", "AutoReturnToCockpit",
                true,
                "Automatically return the camera to your aircraft's cockpit shortly after your last " +
                "in-flight missile detonates (or otherwise despawns).");
            _autoReturnDelay = Config.Bind("Behavior", "AutoReturnDelaySeconds",
                3f,
                "How long to wait, in seconds, after your last missile is gone before auto-returning " +
                "to the cockpit. Only used when AutoReturnToCockpit is enabled.");

            Log.LogInfo($"{MyPluginInfo.PLUGIN_NAME} v{MyPluginInfo.PLUGIN_VERSION} loaded. " +
                        $"Next=[{_cycleNext.Value}] Prev=[{_cyclePrev.Value}] " +
                        $"Return=[{_returnToAircraft.Value}] " +
                        $"AutoReturn=[{(_autoReturnEnabled.Value ? $"{_autoReturnDelay.Value:0.#}s" : "off")}].");
        }

        private void Update()
        {
            // Single-player, live mission only. Otherwise stay out of the way.
            if (!GameBridge.InSinglePlayerMission())
            {
                _tracker.DetachIfNeeded(null);
                _cursor = -1;
                _autoReturnAt = -1f;
                return;
            }

            // Keep the tracker subscribed to the CURRENT local aircraft (handles respawns/aircraft swaps).
            var aircraft = GameBridge.GetLocalAircraft();
            _tracker.EnsureAttached(aircraft);

            if (_cycleNext.Value.IsDown()) Cycle(+1);
            else if (_cyclePrev.Value.IsDown()) Cycle(-1);
            else if (_returnToAircraft.Value.IsDown()) ReturnToAircraft();

            // Check the auto-return timer only about once a second (every 60 frames). A ~1s delay in
            // returning is imperceptible, and this keeps the per-frame work out of the hot path.
            if (Time.frameCount % 60 == 0) UpdateAutoReturn();

            // NOTE: we do NO per-frame camera override. We only switch on a keypress (or the
            // auto-return timer above), using the game's own follow path. The native "Switch View"
            // key (L) is left free to cycle the followed missile's camera angles, and we never touch
            // the (aircraft-driven, 2D) RWR/warning audio path.
        }

        private void Cycle(int direction)
        {
            var missiles = _tracker.LiveMissiles();   // pruned, in launch order
            if (missiles.Count == 0)
            {
                Log.LogInfo("No in-flight missiles of yours to follow.");
                _cursor = -1;
                return;
            }

            _cursor = ((_cursor + direction) % missiles.Count + missiles.Count) % missiles.Count;
            GameBridge.FollowUnit(missiles[_cursor]);
            Log.LogInfo($"Following missile {_cursor + 1}/{missiles.Count}. " +
                        $"Press [{_returnToAircraft.Value}] to return to your aircraft.");
        }

        private void ReturnToAircraft()
        {
            GameBridge.ReturnToAircraft();
            _cursor = -1;   // next cycle starts from the first missile again
            _autoReturnAt = -1f;
            Log.LogInfo("Returned to your aircraft.");
        }

        // Arms a short countdown once we're following a missile and none of ours remain in flight,
        // then snaps back to the cockpit when it elapses. Any new/remaining missile cancels it.
        private void UpdateAutoReturn()
        {
            // Only relevant while the feature is on and we're actively following one of our missiles.
            if (!_autoReturnEnabled.Value || _cursor < 0)
            {
                _autoReturnAt = -1f;
                return;
            }

            // Still have missiles in flight? Cancel any pending countdown and keep watching.
            if (_tracker.LiveMissiles().Count > 0)
            {
                _autoReturnAt = -1f;
                return;
            }

            // No live missiles left: arm the countdown, then fire once it elapses.
            if (_autoReturnAt < 0f)
            {
                float delay = Mathf.Max(0f, _autoReturnDelay.Value);
                _autoReturnAt = Time.time + delay;
                Log.LogInfo($"Last missile gone; returning to your aircraft in {delay:0.#}s.");
            }
            else if (Time.time >= _autoReturnAt)
            {
                Log.LogInfo("Auto-returning to your aircraft (last missile detonated).");
                ReturnToAircraft();   // also clears _autoReturnAt
            }
        }
    }
}